CREATE TABLE kulturkort_partnere (
  id            INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  navn          TEXT         NOT NULL,
  kommune       TEXT         NOT NULL,
  fylke         TEXT         NOT NULL,
  type          TEXT,
  epost         TEXT,
  nettside      TEXT,
  beskrivelse   TEXT,
  kategori      TEXT         NOT NULL DEFAULT 'aktiv'
                               CHECK (kategori IN ('aktiv', 'tidligere', 'potensiell')),
  published     BOOLEAN      GENERATED ALWAYS AS (kategori = 'aktiv') STORED,
  innleggsdato  TEXT,
  oppdatert     TEXT
);

CREATE INDEX kulturkort_partnere_kategori_idx ON kulturkort_partnere (kategori);
CREATE INDEX kulturkort_partnere_kommune_idx  ON kulturkort_partnere (kommune);
CREATE INDEX kulturkort_partnere_fylke_idx    ON kulturkort_partnere (fylke);

ALTER TABLE kulturkort_partnere ENABLE ROW LEVEL SECURITY;

-- Alle kan lese aktive partnere (offentlig side)
CREATE POLICY "Aktive partnere er offentlige"
  ON kulturkort_partnere FOR SELECT
  USING (kategori = 'aktiv');

-- Innloggede ansatte/superadmin ser alle
CREATE POLICY "Ansatt og superadmin ser alle partnere"
  ON kulturkort_partnere FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM profiles p
    WHERE p.id = auth.uid() AND p.rolle IN ('superadmin', 'ansatt')
  ));

-- Kun superadmin kan skrive
CREATE POLICY "Superadmin administrerer kulturkort-partnere"
  ON kulturkort_partnere FOR ALL
  USING (EXISTS (
    SELECT 1 FROM profiles p
    WHERE p.id = auth.uid() AND p.rolle = 'superadmin'
  ));
