-- 021: hall — vanlig vertskap + alternative haller
-- Import fra Hallregister_utkast_2.xlsx (161 nettverk, 16.06.2026)
-- Kjørt i Supabase 11. aug 2026.

alter table haller add column if not exists vanlig_vertskap text;
alter table haller add column if not exists alternative_haller text;

begin;
update haller set vanlig_vertskap = 'Kun Gossen som deltar på kurset. Gå gjennom to og to leker f.eks?', alternative_haller = 'Hall på Gossen.' where nettverk = 'AKT/LEK Aukra' and navn = 'Hall v/Gossen skole';
update haller set vanlig_vertskap = 'Hessa (fast)', alternative_haller = alternative_haller where nettverk = 'Lek Ålesund' and navn = 'Osane idrettshall';
update haller set vanlig_vertskap = 'Sagstad (alltid)', alternative_haller = alternative_haller where nettverk = 'Alver Sør' and navn = 'Meland Aktiv';
update haller set vanlig_vertskap = 'Alversund', alternative_haller = 'Lindåshallen' where nettverk = 'Alver Nord' and navn = 'Alverhallen';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.00', alternative_haller = alternative_haller where nettverk = 'Askvoll' and navn = 'Askvollhallen';
update haller set vanlig_vertskap = 'Strusshamn og Florvåg', alternative_haller = alternative_haller where nettverk = 'Askøy (Arena)' and navn = 'Askøy Arena';
update haller set vanlig_vertskap = 'Tveit', alternative_haller = alternative_haller where nettverk = 'Askøy (Forum)' and navn = 'Askøy Forum';
update haller set vanlig_vertskap = 'Felles, oppmøte 09.00', alternative_haller = alternative_haller where nettverk = 'Austevoll' and navn = 'Selbjørn idrettshall';
update haller set vanlig_vertskap = 'Kaland', alternative_haller = alternative_haller where nettverk = 'Bergen Sør: Fana/Ytrebygda (Kaland)' and navn = 'Kaland idrettshall';
update haller set vanlig_vertskap = 'Sædalen', alternative_haller = alternative_haller where nettverk = 'Bergen Sør: Fana/Ytrebygda (Sædalen)' and navn = 'Sædalen idrettshall';
update haller set vanlig_vertskap = 'Skranevatnet og Liland', alternative_haller = alternative_haller where nettverk = 'Bergen Sør: Fana/Ytrebygda (Sandsli)' and navn = 'Sandslihallen';
update haller set vanlig_vertskap = 'Løvås', alternative_haller = alternative_haller where nettverk = 'Bergen Vest: Fyllingsdalen/Laksevåg (Bøneshallen)' and navn = 'Bøneshallen';
update haller set vanlig_vertskap = 'Bønes', alternative_haller = alternative_haller where nettverk = 'Bergen Vest: Fyllingsdalen/Laksevåg (Bønes Arena)' and navn = 'Bønes Arena';
update haller set vanlig_vertskap = 'Mathopen', alternative_haller = 'Olsvikhallen: Olsvik skole; Vadmyrahallen (torsdag): Vadmyra og søknad; Alvøenhallen: www.bergen.kommune.no/aktivkommune' where nettverk = 'Bergen Vest: Fyllingsdalen/Laksevåg (Alvøen)' and navn = 'Alvøen idrettshall';
update haller set vanlig_vertskap = 'Paradis (eller har Haukeland sjangs?)', alternative_haller = alternative_haller where nettverk = 'Bergenhus/Årstad (Haukelandshallen)' and navn = 'Haukelandshallen';
update haller set vanlig_vertskap = 'Krohnengen', alternative_haller = alternative_haller where nettverk = 'Bergenhus/Årstad (Vitalitetssenteret)' and navn = 'Vitalitetssenteret';
update haller set vanlig_vertskap = 'Mjølkeråen us', alternative_haller = 'Åsane Arena, men vgs benytter og vi må spørre dem. Må da evt. dele kurset i tre. To dager her og en dag i Arna.' where nettverk = 'Bergen Nord: Åsane/Arna' and navn = 'Vestlandshallen';
update haller set vanlig_vertskap = 'Hillestveit og Våge (alltid)', alternative_haller = alternative_haller where nettverk = 'Bømlo' and navn = 'Langevåg Bygdatun - idrettshallen';
update haller set vanlig_vertskap = 'Torvmyrane', alternative_haller = alternative_haller where nettverk = 'Kinn' and navn = 'Florahallen/Florøhallen';
update haller set vanlig_vertskap = 'Norheimsund skole (alltid)', alternative_haller = alternative_haller where nettverk = 'Kvam + Ølve i Kvinnherad' and navn = 'Norheimsund idrettshall';
update haller set vanlig_vertskap = 'Valen', alternative_haller = alternative_haller where nettverk = 'Kvinnherad' and navn = 'Kvinnherad Arena - håndballflate';
update haller set vanlig_vertskap = 'Hjellvik og Valestrand', alternative_haller = alternative_haller where nettverk = 'Lek Osterøy' and navn = 'Osterøyhallen';
update haller set vanlig_vertskap = 'Norane og Leikanger (alltid)', alternative_haller = alternative_haller where nettverk = 'Sogndal, Luster, Aurland' and navn = 'Leikangerhallen (Saften)';
update haller set vanlig_vertskap = 'Hystad', alternative_haller = 'Nysæterhallen (2024/2025);  v/Nysæter ungdomsskole; ; (Solidhallen på kartet); ; Rackethallen på Vikahaugane (Leirvik har booket tidl.)' where nettverk = 'Stord (Solidhallen/Nordbygdohallen)' and navn = 'Nordbygdohallen (2023/2024 + 2025/2026)';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.10 (mulig de eldste fra Tonning kommer 09.00 for å gå gjennom litt tips til gruppeledelse).', alternative_haller = alternative_haller where nettverk = 'Stryn' and navn = 'Strynehallen';
update haller set vanlig_vertskap = 'Naustdal', alternative_haller = 'Gaularhallen vår; Førdehuset idrettshall?' where nettverk = 'Sunnfjord' and navn = 'Naustdalhallen Høst - Skolen har sagt opp - prøve å lande permanent løsning sentralt i Førde:';
update haller set vanlig_vertskap = 'Sveio', alternative_haller = alternative_haller where nettverk = 'Sveio' and navn = 'Vigdartun idrettshall';
update haller set vanlig_vertskap = 'Lægreid', alternative_haller = 'Voss idrettshall; Pris: 2525; ; https://idrettshallen.no/kalender/' where nettverk = 'Voss, Eidfjord og Ulvik' and navn = 'Eidfjordhallen';
update haller set vanlig_vertskap = 'Felles oppmøte 09.30', alternative_haller = 'Sentralhallen (høst); Alternativ Sentralhallen (Sandnes/Bjørnevatn vert): Barentshallen ; ; Fjellhallen, Kirkenes (dersom de kommer tilbake, vinter)' where nettverk = 'LEK Sør-Varanger' and navn = 'Sentralhallen (fast)';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.50', alternative_haller = 'Tana flerbrukshall (evt. vinter)' where nettverk = 'LEK Tana-Vadsø' and navn = 'Vadsøhallen (fast)';
update haller set vanlig_vertskap = 'Aspåsen', alternative_haller = 'Hall på Aspåsen skole fra H25, ca. 1/3 av håndballbane.; Fornøyd med å ha det på skolen, men er trangt og akkurat på grensen.; ; Alt: Mørkvedhallen, Hall B; ; Bankgata flerbrukshall: Booking' where nettverk = 'LEK Bodø' and navn = 'Bankgata flerbrukshall';
update haller set vanlig_vertskap = 'Hemnes sentralskole (alltid)', alternative_haller = alternative_haller where nettverk = 'AKT/LEK Hemnes' and navn = 'Hemnes idretthall (Hemneshallen)';
update haller set vanlig_vertskap = 'Håkvik + Bjerkvik', alternative_haller = alternative_haller where nettverk = 'LEK Narvik' and navn = 'Idrettens hus';
update haller set vanlig_vertskap = 'Kurs på Båsmo.', alternative_haller = 'Ytteren flerbrukshall (alltid)' where nettverk = 'LEK Rana' and navn = 'Båsmo barneskole - gymsal';
update haller set vanlig_vertskap = 'Rognan 6. og 7. trinn.', alternative_haller = alternative_haller where nettverk = 'LEK Saltdal' and navn = 'Rognan idrettshall';
update haller set vanlig_vertskap = 'Olderskog', alternative_haller = 'Mosjøhallen er revet.' where nettverk = 'LEK Vefsn' and navn = 'Kippermoen idrettshall';
update haller set vanlig_vertskap = 'Rundevoll', alternative_haller = 'Rundevoll skole (gymsal), Eikhallen, Norrønhallen (koster 2000kr), Espelandshallen' where nettverk = 'Eigersund, Sokndal, Lund' and navn = 'Egersundshallen';
update haller set vanlig_vertskap = 'Hauge', alternative_haller = alternative_haller where nettverk = 'Haugesund 2 (Vardhallen)' and navn = 'Vardhallen';
update haller set vanlig_vertskap = 'Austrheim', alternative_haller = alternative_haller where nettverk = 'Haugesund 1 (Skåredalen)' and navn = 'Flerbrukshallen på Skåredalen skole.';
update haller set vanlig_vertskap = 'Tau (alltid)', alternative_haller = alternative_haller where nettverk = 'Hjelmeland og Strand' and navn = 'Superparken v/Tau skole';
update haller set vanlig_vertskap = 'Stangaland', alternative_haller = alternative_haller where nettverk = 'Karmøy 1' and navn = 'Storhallen';
update haller set vanlig_vertskap = 'Torvastad', alternative_haller = alternative_haller where nettverk = 'Karmøy 2' and navn = 'Storhallen';
update haller set vanlig_vertskap = 'Bore', alternative_haller = 'Orrehallen, Klepphallen, Borehallen' where nettverk = 'Klepp' and navn = 'Borehallen';
update haller set vanlig_vertskap = 'Harestad', alternative_haller = alternative_haller where nettverk = 'Randaberg' and navn = 'Randaberghallen - Hall 2';
update haller set vanlig_vertskap = 'Hana + Vatneli us*', alternative_haller = 'Kleivanehallen' where nettverk = 'Sandnes (Hana)' and navn = 'Hanahallen';
update haller set vanlig_vertskap = 'Stangeland + Tryggheim', alternative_haller = 'Giskehallen (vanskelig å booke); Kleivanehallen' where nettverk = 'Sandnes (Sandneshallen)' and navn = 'Sandneshallen';
update haller set vanlig_vertskap = 'Storevarden', alternative_haller = 'Folkehallene Forus; Dere kan få gratis parkering, bare oppgi registreringsnummer på bilene deres i resepsjon når dere kommer den morgningen- så ordner de det😊; ; Tanangerhallen; Skadberghallen' where nettverk = 'Sola' and navn = 'Skadberghallen';
update haller set vanlig_vertskap = 'Skeie', alternative_haller = alternative_haller where nettverk = 'Stavanger (Hundvåghallen); ; NB! To kursholdere' and navn = 'Hundvåghallen';
update haller set vanlig_vertskap = 'Finnøy', alternative_haller = 'Rennesøyhallen - Vikevåg; Mastrahallen v/Mosterøy skole' where nettverk = 'Stavanger (Rennesøy/Finnøy)' and navn = 'Finnøyhallen';
update haller set vanlig_vertskap = 'Byfjord', alternative_haller = alternative_haller where nettverk = 'Stavanger (Gautesetehallen)' and navn = 'Gautesete idrettshall';
update haller set vanlig_vertskap = 'Kvernevik 6.-7. trinn', alternative_haller = alternative_haller where nettverk = 'Stavanger (Kvernevikhallen)' and navn = 'Kvernevikhallen';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = 'Vikinghallen, håndballhall eller fotballhall må avklares med booking.' where nettverk = 'Ungdomsskoler Stavanger, Sandnes, Strand';
update haller set vanlig_vertskap = 'Rosseland', alternative_haller = alternative_haller where nettverk = 'Time' and navn = 'Lyehallen';
update haller set vanlig_vertskap = 'Grinde', alternative_haller = 'Skjoldhallen; Tysvær arena' where nettverk = 'Tysvær og Bokn' and navn = 'Skjoldhallen';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.50', alternative_haller = alternative_haller where nettverk = 'Lek Senja' and navn = 'Senja Storhall 1/3';
update haller set vanlig_vertskap = 'Solneset', alternative_haller = 'Hamnahallen (gratis, men kald, ingen musikkspiller); ; Potensielle haller: Skarp IF er Skarphallen. KSK(Kvaløya sportsklubb er vel Storelvahallen, TUIL arena er Tromsdalen UIL, og ; Lerøyhallen? Tromsøhallen?; ; Ikke aktuelle ; Tromsdalshallen - Tromsdalen vgs, kan ikke si noe før etter sommeren.; Gyllenborg idrettshall og Breivikahallen er for liten.' where nettverk = 'LEK Tromsø 2' and navn = 'Stakkevollan idrettshall';
update haller set vanlig_vertskap = 'Reinen', alternative_haller = alternative_haller where nettverk = 'LEK Tromsø 1' and navn = 'Kroken idrettshall v/Kroken skole.';
update haller set vanlig_vertskap = 'Harstad', alternative_haller = 'Hålogalandshallen (fast?); ; NB! Ta kontakt en uke før, for å avtale opplåsing/nøkkel.; NB! Rydd unna baller!; Husk musikkanlegg.; ; NB! Ikke Krafthallen på vinter - iskald! Dårlige fasiliteter.' where nettverk = 'LEK Harstad' and navn = 'Hålogalandshallen';
update haller set vanlig_vertskap = '6. og 7. trinn på Enge', alternative_haller = alternative_haller where nettverk = 'Etne og Vindafjord' and navn = 'Etne idrettshall (Skakkehallen)';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 1' and navn = 'Gymsalen + musikkrom på Munkerud skole';
update haller set vanlig_vertskap = 'Voksen (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 2' and navn = 'Voksenhallen';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 3' and navn = 'Tåsen skole gymsal';
update haller set vanlig_vertskap = 'Rødtvet H26', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 4' and navn = 'Grorud flerbrukshall';
update haller set vanlig_vertskap = 'Ekeberg (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 5' and navn = 'Ekeberg skole flerbrukshall';
update haller set vanlig_vertskap = 'Skøyen (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 6' and navn = 'Skøyenhallen';
update haller set vanlig_vertskap = 'Grefsen (30stk, alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 7' and navn = 'Grefsenhallen';
update haller set vanlig_vertskap = 'Rosenholm - ikke ønskelig. Må forespørre andre.', alternative_haller = 'Klemetsrud idrettspark' where nettverk = 'LEK Oslo 8' and navn = 'Holmliahallen';
update haller set vanlig_vertskap = 'Nordseter H26', alternative_haller = 'Kastellet fleridrettshall; (Ikke håndballstørrelse)' where nettverk = 'LEK Oslo 9' and navn = 'Nordseter fleridrettshall';
update haller set vanlig_vertskap = 'Vestli (allitd)', alternative_haller = alternative_haller where nettverk = 'LEK Oslo 10' and navn = 'Vestli flerbrukshall';
update haller set vanlig_vertskap = 'Sodin (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Heim' and navn = 'Hemnehallen';
update haller set vanlig_vertskap = 'Sveberg (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Malvik' and navn = 'Sveberghallen';
update haller set vanlig_vertskap = 'Grøtte H26', alternative_haller = 'Glimtbanen på Gjølme' where nettverk = 'LEK Orkland' and navn = 'Orklahallen';
update haller set vanlig_vertskap = 'Egge H26', alternative_haller = alternative_haller where nettverk = 'LEK Steinkjer' and navn = 'Steinkjerhallen- friidrettshallen';
update haller set vanlig_vertskap = 'Fosslia H26', alternative_haller = alternative_haller where nettverk = 'LEK Stjørdal' and navn = 'Stjørdalshallen';
update haller set vanlig_vertskap = 'Hårstad H26', alternative_haller = alternative_haller where nettverk = 'LEK Trondheim 1' and navn = 'Rostenhallen';
update haller set vanlig_vertskap = 'Lilleby H26', alternative_haller = alternative_haller where nettverk = 'LEK Trondheim 2' and navn = 'Leangenhallen';
update haller set vanlig_vertskap = 'Flatåsen (alltid)', alternative_haller = 'Flatåshallen - fotballhallen (vinter)' where nettverk = 'LEK Trondheim 3' and navn = 'Flatåsen kunstgress (høst)';
update haller set vanlig_vertskap = 'Nardo H26', alternative_haller = alternative_haller where nettverk = 'LEK Trondheim 4' and navn = 'Utleirahallen';
update haller set vanlig_vertskap = 'Byåsen H26', alternative_haller = 'Åsveihallen' where nettverk = 'LEK Trondheim 5' and navn = 'Munkvollhallen';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = alternative_haller where nettverk = 'LEK Ørland' and navn = 'Bjugnhallen';
update haller set vanlig_vertskap = 'Oserød H26', alternative_haller = alternative_haller where nettverk = 'LEK Færder' and navn = 'Hårkollhallen';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = alternative_haller where nettverk = 'LEK Holmestrand' and navn = 'Selvikhallen';
update haller set vanlig_vertskap = 'Bokemoa', alternative_haller = alternative_haller where nettverk = 'LEK Sandefjord 1' and navn = 'Runarhallen';
update haller set vanlig_vertskap = 'Høyjord* og Unneberg H26', alternative_haller = alternative_haller where nettverk = 'LEK Sandefjord 2' and navn = 'Runarhallen';
update haller set vanlig_vertskap = 'Hurrød', alternative_haller = 'Gressvikhallen (Hurrød) Info Gressvikhallen: Ann Kristin er i hallen fra kl. 8 og tar i mot kursholder. Gå inn ved parkeringen nede ved utøverinngangen.' where nettverk = 'Lek Fredrikstad 2' and navn = 'Gressvikhallen (Hurrød)';
update haller set vanlig_vertskap = 'Konnerud H26', alternative_haller = 'Gulskogenhallen' where nettverk = 'LEK Drammen 1' and navn = 'Konnerud kunstgress';
update haller set vanlig_vertskap = 'Gulskogen', alternative_haller = alternative_haller where nettverk = 'LEK Drammen EKSTRA H26' and navn = 'Gulskogenhallen';
update haller set vanlig_vertskap = 'Øren (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Drammen 2' and navn = 'Øren flerbrukshall';
update haller set vanlig_vertskap = 'Skoger H26', alternative_haller = 'Glassverkethallen (vinter)' where nettverk = 'LEK Drammen 3' and navn = 'Skogerhallen (høst)';
update haller set vanlig_vertskap = 'Brandengen (to av trinnene).', alternative_haller = alternative_haller where nettverk = 'LEK Drammen 4' and navn = 'Brandengen flerbrukshall';
update haller set vanlig_vertskap = 'Solberg H26', alternative_haller = 'Ekneshallen (vinter)' where nettverk = 'LEK Drammen 5' and navn = 'Solberg kunstgress H26';
update haller set vanlig_vertskap = 'Gol H26', alternative_haller = 'Ål idrettshall (vinter)' where nettverk = 'LEK Hallingdal' and navn = 'Gol idrettsarena (høst)';
update haller set vanlig_vertskap = 'Hole us (alltid)', alternative_haller = 'Kleivhallen - Sundvollen ansvar' where nettverk = 'LEK Hole utgår sannsynligvis, Sundvollen får tilbud om å reise til Lek Bærum 1' and navn = 'Flerbrukshallen på Hole us';
update haller set vanlig_vertskap = 'Tranby us (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Lier' and navn = 'Hallen på Hegg skole';
update haller set vanlig_vertskap = 'Stalsberg H26', alternative_haller = 'Åmot stadion' where nettverk = 'LEK Modum' and navn = 'Sparebank 1-hallen (fotballhallen) i Vikersund hoppsenter.';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = alternative_haller where nettverk = 'LEK Ringerike' and navn = 'Ullerålhallen';
update haller set vanlig_vertskap = 'Felles opplæring (alltid)', alternative_haller = 'Eidskoghallen (vinter); Gymsalen på Magnor skole (høst)' where nettverk = 'LEK Eidskog' and navn = 'Gymsal Magnor skole ok booket av Kevin Bjørndalen Magnor skole';
update haller set vanlig_vertskap = 'Frydenlund', alternative_haller = 'Frydenlund sin hall er for liten.; ; Åmot skole; ; Innbygda vert: Trysil FK fotballhall. Vestsideveien, 2420 Trysil. ; Det er en ganske kald hall så greit å ha med/på seg bukse og genser/jakke.; ; Frydenlund ønsker vertskap H26, skal se på muligheter for større hall. evt. ute?' where nettverk = 'LEK Elverum og Rena' and navn = 'Hallen på Ydalir skole, Mari på Frydenlund skole har booket ok Adresse hall: Granittvegen 4, 2413 Elverum';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.00', alternative_haller = 'Kan vi låne Presterudhallen (håndballhall): benyttes av Prestrud og må avtales med dem.; ; Obos-hallen (tidligere Sparebankhallen) v/Prestrud skole; ; Kunstgressbane Børstad ungdomsskole? Ajer ungdomsskole? Storhamar?' where nettverk = 'LEK Hamar' and navn = 'Gymsal Rollsløkken skole ok Aleksander Rollsløkken';
update haller set vanlig_vertskap = 'Vennersberg', alternative_haller = 'Hall Glommasvingen skole?' where nettverk = 'LEK Kongsvinger' and navn = 'Kongsvingerhallen';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.15', alternative_haller = 'Sør-Aurdalshallen (vinter) - Bagn skole. Kan benyttes begge terminer ved behov.; ; Rogne skule (høst) VELDIG liten hall. Ingenting annet v/Rogne enn mot Beitostølen. ; ; Valdreshallen benyttes av Nord-Aurdal ungdomsskole - ikke intr i å dele.; ; Valdres storhall ; Pris: 1735  ; Benyttes normalt av vgs. Tirsdag er dum dag.' where nettverk = 'Lek Valdres' and navn = 'Valdres storhall';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.15', alternative_haller = 'Dokkahallen (vinter)?; Gymsalen på Raufoss = liten; Raufosshallen (høst) - Raufoss booker. TLA adgangskort?' where nettverk = 'LEK Vestre Toten' and navn = 'Dokkahallen ok, booket av Stine- Raufoss ønsker ikke å delta, skal organisere selv';
update haller set vanlig_vertskap = 'Hoffsvangen', alternative_haller = 'Skreiahallen (vinter); ; Kontaktperson hall: Vidar Buflaten: 95048620; ; Skreia stadion/hallen ved dårlig vær (høst)' where nettverk = 'LEK Østre Toten' and navn = 'Skreia stadion evt hall ved dårlig vær';
update haller set vanlig_vertskap = 'Solvang (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Øyer' and navn = 'Øyerhallen';
update haller set vanlig_vertskap = 'Rekustad', alternative_haller = 'Rolvsøyhallen (Rekustad); ; ; Forslag fra Sagabakken:; Kongstenhallen - ; Nøklebyhallen; Borgehallen; Østfoldhallen' where nettverk = 'Lek Fredrikstad 1' and navn = 'Rolvsøyhallen (Rekustad)';
update haller set vanlig_vertskap = 'Grålum (alltid)', alternative_haller = alternative_haller where nettverk = 'Lek Sarpsborg 1' and navn = 'Grålumhallen ok Anita Ødegaard';
update haller set vanlig_vertskap = 'Hornnes og Ullerøy', alternative_haller = alternative_haller where nettverk = 'Lek Sarpsborg 2' and navn = 'Skjeberghallen - hall B';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = 'Høst: Skiptvet kunstgress/Hall i backup; Vinter: Skiptvethallen' where nettverk = 'Lek Skiptvet/Råde/Moss' and navn = 'Skiptvet kunstgress ok hall i backup ok';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = 'Fjellheim idrettshall/Spydeberghallen ; (Må skaffe oss eller låne adgangskort til hallen); Fjellhallen' where nettverk = 'Lek Spydeberg' and navn = 'Fjellhallen';
update haller set vanlig_vertskap = 'Felles opplæring fra 09.30', alternative_haller = alternative_haller where nettverk = 'AKT Agder' and navn = 'Fevikhallen';
update haller set vanlig_vertskap = 'Hisøy H26', alternative_haller = 'Nedeneshallen (vinter)' where nettverk = 'LEK Arendal/Froland' and navn = 'Hisøyhallen (høst)';
update haller set vanlig_vertskap = 'Farsund H26', alternative_haller = alternative_haller where nettverk = 'LEK Farsund' and navn = 'Alcoahallen';
update haller set vanlig_vertskap = 'Liknes H26', alternative_haller = alternative_haller where nettverk = 'LEK Flekkefjord/Kvinesdal/Sirdal' and navn = '*Flekkefjord Sparebank Arena';
update haller set vanlig_vertskap = 'Holviga H26', alternative_haller = 'Vikhallen (vinter)' where nettverk = 'LEK Grimstad' and navn = 'Holvikahallen (høst)';
update haller set vanlig_vertskap = 'Hellemyr (alltid)', alternative_haller = alternative_haller where nettverk = 'LEK Kristiansand 1' and navn = 'Hellemyrhallen';
update haller set vanlig_vertskap = 'Ve H26', alternative_haller = alternative_haller where nettverk = 'LEK Kristiansand 2' and navn = 'Tveithallen';
update haller set vanlig_vertskap = 'Lovisenlund', alternative_haller = 'Odderøyhallen; ; -Vi har fått tips om Odderøyhallen, men den koster 750kr per time 18.05.26.' where nettverk = 'LEK Kristiansand 4' and navn = 'Håneshallen';
update haller set vanlig_vertskap = 'Birkeland', alternative_haller = 'Høvåghallen (vinter); tingsaker flerbrukshall' where nettverk = 'LEK Lillesand' and navn = 'Birkeneshallen (høst)';
update haller set vanlig_vertskap = 'Furulunden H26', alternative_haller = 'Frøyslandshallen (vinter); (utfordrende med onsdager da hallen leies ut)' where nettverk = 'LEK Lindesnes/Mandal' and navn = 'Mandalshallen (høst)';
update haller set vanlig_vertskap = 'LKG og Årnes H26', alternative_haller = alternative_haller where nettverk = 'LEK Lyngdal' and navn = '*Fibohallen';
update haller set vanlig_vertskap = 'Abel H26', alternative_haller = 'Torbjørnshall, Risørhallen, Lyngmyrhallen' where nettverk = 'LEK Risør/Tvedestrand/Gjertstad' and navn = 'Torbjørnshall';
update haller set vanlig_vertskap = 'Vennesla (H26)', alternative_haller = 'Torridalshallen (vinter); NB: bruk skilleveggene i hallen.' where nettverk = 'LEK Vennesla' and navn = 'Venneslahallen (høst)';
update haller set vanlig_vertskap = 'Løken', alternative_haller = 'Hølandshallen (høst - Løken skole); Aursmoen skole (vinter)' where nettverk = 'Lek Aurskog/Høland' and navn = 'Hølandshallen';
update haller set vanlig_vertskap = 'Evje', alternative_haller = 'Høst = ute: Hauger kunstgress v/Rosenvilde vgs; ; Toaletter i klubbhuset til BVH IF fotball. NB! Sjekk at toalett ser ok ut. Rydd og tørk evt av dersom det er grisete!; Vinter = inne; ; Bærum idrettspark (uaktuell vinter), ; Holmenhallen; ; Stabekk kunstgress, Høvikbanen; Rykkinnhallen (fredager, Ander daglig leder: 982 04 807); Helsethallen (brukt tidligere); ; Undersøkt med Haslum idrettslag og kunstgresset deres.; Tiden er til Nadderud vgs og idrettsbarnehagen.' where nettverk = 'Lek Bærum 1' and navn = 'Hauger kunstgress';
update haller set vanlig_vertskap = 'Blommenholm', alternative_haller = 'Se notater på Bærum 1' where nettverk = 'Lek Bærum 2' and navn = 'Hauger kunstgress';
update haller set vanlig_vertskap = 'Dal', alternative_haller = '-Flerbrukshallen på Råholt skole (vinter); -Dal stadion (høst og om Dal er vertskap); -Fotballbanen på Bønsmoen skole; ; -Råholthallen som backup' where nettverk = 'LEK Eidsvoll' and navn = 'Dal stadion';
update haller set vanlig_vertskap = 'Åsenhagen', alternative_haller = alternative_haller where nettverk = 'LEK Gjerdrum' and navn = 'Gjerdrumshallen';
update haller set vanlig_vertskap = 'Gjellerås', alternative_haller = 'Marikollhallen? Rælingen vgs og Marikollen us benytter den.; ; Utekurs høst?' where nettverk = 'Lek Lillestrøm 1 (Skedsmo)' and navn = 'Slorahallen';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = 'Eika Fet arena?' where nettverk = 'Lek Lillestrøm 2 (Fet)' and navn = 'Fethallen';
update haller set vanlig_vertskap = 'Sørumsand', alternative_haller = 'Høst: Sørumsand kunstgress + SIF hallen i backup; Nøkkel hentes på Sørumsand skole; ; Frognerhallen (2 håndballlflater); (Trenger nøkkelkort for å komme inn - lag en god avtale)' where nettverk = 'Lek Lillestrøm 3 (Sørum)' and navn = 'Sørumsand kunstgress';
update haller set vanlig_vertskap = 'Benterud 6.-7.trinn?', alternative_haller = 'Thonhallen; Rolvsrud kunstgress: John Carew banen' where nettverk = 'Lek Lørenskog - Benterudhallen' and navn = 'Benterudhallen';
update haller set vanlig_vertskap = 'Preståsen', alternative_haller = 'Maurahallen brukes på vinteren og Nannestadhallen er i back up på høsten.; ; På kunstgresset Nannestad stadion på høsten, evt. Nannestadhallen (ved dårlig vær)' where nettverk = 'LEK Nannestad' and navn = 'Kunstgress Nannestad stadion';
update haller set vanlig_vertskap = 'Felles opplæring', alternative_haller = 'Nannestad stadion/hallen ved dårlig vær (høst)' where nettverk = 'AKT Nannestad' and navn = 'Nannestadhallen';
update haller set vanlig_vertskap = 'Nesoddtangen skole', alternative_haller = 'Nesoddtangen ønsker å være vertskap. Får egen hall H27, men har gåavstand til Nesoddhallen.' where nettverk = 'Lek Nesodden' and navn = 'Nesoddhallen';
update haller set vanlig_vertskap = 'Sofiemyr', alternative_haller = 'Kunstgresset på Sofiemyr/Sofiemyr idrettshall i backup - vertskapet booker denne (Tårnåsen/Sofiemyr) - Skolen kan ikke la oss bruke hallen, og har ikke myndighet til å låne oss kunsgresset per 02.06.26. ; Greverudhallen (vinter); ; -Vassbonn og Østli: kan bruke kunstgress ute på høsten. De har samme kunstgress. Det har visst vært flere kurs der tidligere. ; -Kolbotn: Har tilgang på egen hall (hånballbane) ved skolen og kan være vertskap. -> Kolbotn idrettshall; -Tårnåsen - Kan være vertskap i Sofiemyrhallen.' where nettverk = 'Lek Oppegård' and navn = 'Østre Greverud Idrettshall';
update haller set vanlig_vertskap = 'Follo barne- og ungdomsskole', alternative_haller = alternative_haller where nettverk = 'Lek Follo barne- og ungdomsskole(spesialskole)' and navn = 'Hall på skolen';
update haller set vanlig_vertskap = 'Hebekk og Finstad', alternative_haller = alternative_haller where nettverk = 'Lek Ski' and navn = 'Stil arena';
update haller set vanlig_vertskap = 'Sagdalen', alternative_haller = 'Forslag haller fra V26; - Skedsmohallen (mange skoler inn -vgs og kombi); - Sandbekkhallen - Sandbekken us, evt en tirs?; - Tærudhallen - Tæruddalen skole; - Vollahallen - Skedsmo vgs' where nettverk = 'Lek Rælingen' and navn = 'Slorahallen';
update haller set vanlig_vertskap = 'Hovin og Jessheim', alternative_haller = alternative_haller where nettverk = 'LEK Ullensaker' and navn = 'Jessheim is- og flerbrukshall (UKI Arena)';
update haller set vanlig_vertskap = 'Sjøskogen', alternative_haller = alternative_haller where nettverk = 'Lek Ås' and navn = 'Hallen på Solberg skole';
update haller set vanlig_vertskap = 'Felles opplæring kl. 09.00', alternative_haller = alternative_haller where nettverk = 'Lek Røyken' and navn = 'Hall/gymsal på Folkestad skole';
update haller set vanlig_vertskap = vanlig_vertskap, alternative_haller = 'Slattumhallen (tidl.); Rotneshallen benyttes av Nittedal us og de er ikke villig til å låne bort.; Elvetangenhallen v/Elvetangen skole' where nettverk = 'LEK Nittedal';
commit;

select count(*) filter (where vanlig_vertskap is not null) as med_vertskap,
       count(*) filter (where alternative_haller is not null) as med_alt
from haller;